version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'TeacherDB'
      # So you don't have to use root, but you can if you like
      # You can use whatever password you like
      # Password for root access
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 'codingroot1!'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    extra_hosts:

      - 'host.docker.internal:172.17.0.1'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: